### ISSUE TITLE
Feature for  crawled data to be returned in JSON.

### ISSUE THREAD

**Issue by Dev-29** [Dev-29/sitemap-crawler#3]
Add a feature that returns the crawled data in JSON Format.

**Comment by BDadmehr0** [comment]
Hi, I really like your repository and would like to contribute. From what I understand, the code finds the sitemaps of websites, searches through them, and retrieves all the URLs along with their status codes and other related information.

The task we are going to work on is to output the results in JSON format and store the SEO data in a separate JSON file.

**Comment by BDadmehr0** [comment]
Compared to [pull request 4](https://github.com/Dev-29/sitemap-crawler/pull/4) and testing the program whether it works properly or not, it is better to close these issues

**Comment by Dev-29** [comment]
Thanks for the contribution. Will be closing the issue now.
